# Generated by Django 2.0.3 on 2018-11-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181117_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='numberOfToppings',
            field=models.IntegerField(default=0),
        ),
    ]
