# Generated by Django 2.0.3 on 2018-11-18 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181117_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='typeOfPizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='orders.TypeOfPizza'),
        ),
        migrations.AlterField(
            model_name='priceofpizza',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices_of_pizza', to='orders.Pizza'),
        ),
    ]
