# Generated by Django 2.0.3 on 2018-11-18 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20181117_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceofsub',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices_of_sub', to='orders.Sub'),
        ),
    ]
