# Generated by Django 2.0.3 on 2018-11-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20181118_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeOfPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizeOfPizzas', to='orders.Size')),
            ],
        ),
        migrations.RemoveField(
            model_name='priceofpizza',
            name='size',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='prices',
            field=models.ManyToManyField(through='orders.PriceOfPizza', to='orders.SizeOfPizza'),
        ),
        migrations.AlterField(
            model_name='priceofdinner',
            name='dinner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices_of_dinner', to='orders.Dinner'),
        ),
        migrations.AddField(
            model_name='priceofpizza',
            name='sizeOfPizza',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.SizeOfPizza'),
            preserve_default=False,
        ),
    ]
