# Generated by Django 2.0.3 on 2018-11-20 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20181120_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeofpizza',
            name='typeOfPizza',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.TypeOfPizza'),
            preserve_default=False,
        ),
    ]
