# Generated by Django 2.0.3 on 2018-11-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_sizeofpizza_typeofpizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='typeOfPizza',
        ),
    ]
