# Generated by Django 2.0.3 on 2018-11-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20181120_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pasta',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='salad',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
