# Generated by Django 2.0.3 on 2018-12-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20181201_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_delivered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
